### ISSUE TITLE
[BUG] Plugin gives incorrect player at vote

### ISSUE THREAD

**Issue by prefislt** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#13] opened 2021-09-02 15:55 UTC
**Describe the bug**
Sometimes %player% doesn't update when new player votes and reward goes to random player (maybe who previously voted).

**To Reproduce**
I don't really know how to reproduce it. It sometimes gives reward to correct player but sometimes to someone else.

**Expected behavior**
%player% should update currectly with every player vote.

**Screenshots**
https://prnt.sc/1r1re8z

**Server Info (please complete the following information):**
Minecraft 1.17.1 (Purpur-1368)
Java 16
VoteRewards v5.1.0
NuVotifier v2.7.3

**Comment by GeorgeV220** [comment] 2021-09-02 16:15
Are you using file storage or a database?

**Comment by prefislt** [comment] 2021-09-02 16:46
I'm using default option `type: File`. 

btw. server is on `online-mode=false` maybe that messing things up?

**Comment by GeorgeV220** [comment] 2021-09-02 17:39
can i give you a test jar ??

**Comment by prefislt** [comment] 2021-09-02 17:52
Yes.

**Comment by GeorgeV220** [comment] 2021-09-02 17:54
[voterewards-v5.1.0.zip](https://github.com/GeorgeV220/VoteRewards/files/7100795/voterewards-v5.1.0.zip)
Please enable prevote, aftervote and useless info in debug section

**Comment by prefislt** [comment] 2021-09-02 18:36
What changes did you make? And if there a command to reload configuration?

Right now after a few players votes it show random player but gives reward to currect one. https://prnt.sc/1r23ldj

**Comment by GeorgeV220** [comment] 2021-09-02 19:19
in order to reload configuration do ./vr reload ^-^ (not all values are reloadable tho)
i'm testing if Bukkit#getOfflinePlayer(name) was the issue. Probably i found the cause!! You really helped me thank you very much for your feedback

**Comment by prefislt** [comment] 2021-09-02 21:46
**/vr reload** command doesn't work for me. Glad to help. :)

**Comment by GeorgeV220** [comment] 2021-09-03 01:42
> **/vr reload** command doesn't work for me. Glad to help. :)

It gives you errors or something?? That's kinda interesting

**Comment by prefislt** [comment] 2021-09-03 10:52
Command doesn't exist, getting "Unknown command" error.

**Comment by GeorgeV220** [comment] 2021-09-03 11:20
That's impossible, the command is `voterewards reload` but `vr` is the command allias..

**Comment by prefislt** [comment] 2021-09-03 13:25
I have disabled all commands in configuration file but there is no option to disable "reload" command, maybe it connected to one of other commands?
```
  commands: #Disable or enable plugin commands
    rewards: false
    vote: false
    votetop: false
    voterewards: false
    votes: false
    fakevote: false
    voteparty: false
    hologram: false
```

**Comment by GeorgeV220** [comment] 2021-09-03 16:09
> I have disabled all commands in configuration file but there is no option to disable "reload" command, maybe it connected to one of other commands?
> 
> ```
>   commands: #Disable or enable plugin commands
>     rewards: false
>     vote: false
>     votetop: false
>     voterewards: false
>     votes: false
>     fakevote: false
>     voteparty: false
>     hologram: false
> ```

Enable voterewards command if you want to use voterewards command and all the subcommands of it 😄 
also enable fakevote if you want to do tests votes to a staff member or you :) 
with votes command players can see their/others votes and with vote command you can add the vote links (all messages are editable on messages.yml)

**Comment by prefislt** [comment] 2021-09-03 16:54
Got it. When new version coming out?

**Comment by GeorgeV220** [comment] 2021-09-03 16:56
> Got it. When new version coming out?

When i have time to finish the changes, your problem is fixed with the custom jar i sent you right ?

**Comment by prefislt** [comment] 2021-09-03 17:51
Just did some testing and i don't think so. Still gives incorrect player + got one error message.

```
[17:41:41 INFO]: [Votifier] Got a protocol v1 vote record from /**.**.**.**:34188 -> Vote (from:MINELIST.LT username:VisualGaming address:**.**.**.** timeStamp:1630690901 additionalData:null)
[17:41:41 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Pre process of vote Vote (from:MINELIST.LT username:VisualGaming address:**.**.**.** timeStamp:1630690901 additionalData:null)
[17:41:41 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=VisualGaming, votes=0, servicesLastVote={}, services=[], uuid=df8e6b58-cb8f-3f3c-8b6d-8e51319e4523, voteparty=0}
[17:41:41 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Player XpBoyHub is offline!
[17:41:42 INFO]: Karolisss001 issued server command: /balsuoti
[17:41:49 INFO]: minecraft issued server command: /balsuoti
[17:41:49 INFO]: [Votifier] Got a protocol v1 vote record from /**.**.**.**:34798 -> Vote (from:MINELIST.LT username:Galwwe address:**.**.**.** timeStamp:1630690909 additionalData:null)
[17:41:49 ERROR]: Could not pass event VotifierEvent to VoteRewards vv5.1.0
java.lang.NullPointerException: Cannot invoke "com.georgev22.voterewards.utilities.player.User.getUniqueId()" because the return value of "com.georgev22.voterewards.externals.utilities.maps.ObjectMap.get(Object)" is null
at com.georgev22.voterewards.utilities.player.UserVoteData.getPlayerID(UserVoteData.java:56) ~[voterewards-v5.1.0.jar:?]
at com.georgev22.voterewards.listeners.VotifierListener.onVote(VotifierListener.java:29) ~[voterewards-v5.1.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor301.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1372]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1372]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1372]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1372]
at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[nuvotifier.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1372]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1372]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1372]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1372]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1372]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1372]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1372]
at java.lang.Thread.run(Thread.java:831) [?:?]
[17:42:27 INFO]: [Votifier] Got a protocol v1 vote record from /**.**.**.**:37006 -> Vote (from:MINELIST.LT username:minecraft address:**.**.**.** timeStamp:1630690947 additionalData:null)
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Pre process of vote Vote (from:MINELIST.LT username:minecraft address:**.**.**.** timeStamp:1630690947 additionalData:null)
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=minecraft, votes=0, servicesLastVote={}, services=[], uuid=ee24622f-f3c6-354c-b4e5-efd9833bf950, voteparty=0}
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=minecraft, votes=0, servicesLastVote={}, services=[], uuid=ee24622f-f3c6-354c-b4e5-efd9833bf950, voteparty=0}
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {MINELIST.LT=1630690947997}
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=1, last=1630690947997, daily=1, name=minecraft, votes=1, servicesLastVote={MINELIST.LT=1630690947997}, services=[], uuid=ee24622f-f3c6-354c-b4e5-efd9833bf950, voteparty=0}
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] RUNNING COMMANDS FOR PLAYER: minecraft
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Vote for player CraftPlayer{name=minecraft}
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Votes: 1
[17:42:27 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Last Voted: 2021-09-03T17:42:27.997Z
[17:42:27 INFO]: CONSOLE issued server command: /eco give minecraft 100
[17:42:49 INFO]: [Votifier] Got a protocol v1 vote record from /**.**.**.**:38360 -> Vote (from:MINELIST.LT username:Karolisss001 address:**.**.**.** timeStamp:1630690969 additionalData:null)
[17:42:49 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Pre process of vote Vote (from:MINELIST.LT username:Karolisss001 address:**.**.**.** timeStamp:1630690969 additionalData:null)
[17:42:49 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=Karolisss001, votes=0, servicesLastVote={}, services=[], uuid=2921b786-6cb6-3dff-ad58-b36fb27ba45a, voteparty=0}
[17:42:49 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Player Aride is offline!
[17:43:24 INFO]: [Votifier] Got a protocol v1 vote record from /**.**.**.**:40396 -> Vote (from:MINELIST.LT username:TitanasKestutis address:**.**.**.** timeStamp:1630691004 additionalData:null)
[17:43:24 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Pre process of vote Vote (from:MINELIST.LT username:TitanasKestutis address:**.**.**.** timeStamp:1630691004 additionalData:null)
[17:43:24 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=TitanasKestutis, votes=0, servicesLastVote={}, services=[], uuid=04197af3-d049-3f26-bb4c-885153ec22aa, voteparty=0}
[17:43:24 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Player karolisa is offline!
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=labadenazemele, votes=0, servicesLastVote={}, services=[], uuid=e6ce963a-a4be-314b-951a-a2018f9f1524, voteparty=0}
[17:43:40 INFO]: [Votifier] Got a protocol v1 vote record from /**.**.**.**:41278 -> Vote (from:MINELIST.LT username:kamilukse address:**.**.**.** timeStamp:1630691020 additionalData:null)
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Pre process of vote Vote (from:MINELIST.LT username:kamilukse address:**.**.**.** timeStamp:1630691020 additionalData:null)
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=kamilukse, votes=0, servicesLastVote={}, services=[], uuid=a994fd40-4466-32c4-8649-adf767f83953, voteparty=0}
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=0, last=0, daily=0, name=kamilukse, votes=0, servicesLastVote={}, services=[], uuid=a994fd40-4466-32c4-8649-adf767f83953, voteparty=0}
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {MINELIST.LT=1630691020483}
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] {totalvotes=1, last=1630691020483, daily=1, name=kamilukse, votes=1, servicesLastVote={MINELIST.LT=1630691020483}, services=[], uuid=a994fd40-4466-32c4-8649-adf767f83953, voteparty=0}
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] RUNNING COMMANDS FOR PLAYER: kamilukse
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Vote for player CraftPlayer{name=kamilukse}
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Votes: 1
[17:43:40 INFO]: [VoteRewards] [Debug] [Version: v5.1.0] Last Voted: 2021-09-03T17:43:40.483Z
[17:43:40 INFO]: CONSOLE issued server command: /eco give kamilukse 100 
```

**Comment by GeorgeV220** [comment] 2021-09-03 18:09
Thank you for your report!! Please contact me on discord GeorgeV22#3200

**Closed as completed** 2021-09-06 13:58 UTC
Labels: bug
